spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/password_reset?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
#    username: root
    url: jdbc:mysql://localhost:3306/SPBTForm
    username: root
    password: Nadmin123$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        dialect: org.hibernate.dialect.MySQL8Dialect   



 
  
     
   
    
      
     
    
       
        